server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:futurowork}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: messages
jwt:
  secret: ChangeThisSecretForDev
  expiration: 86400000
spring:
  cache:
    type: caffeine
